version: '3'
services:
  ruby:
    image: anonymizer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/anonymizer
    environment:
      - RUBY_ENV=magento2
    env_file:
      - database.env
    command: ['bash', '-c', 'sleep 60000']
