version: '3'
services:
  anonymizer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUBY_ENV=magento2
    env_file:
      - config/env/database.env
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_USER=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_PASSWORD=magento2

